on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Stop Bot
        uses: garygrossgarten/github-action-ssh@release
        continue-on-error: true
        with:
          command: screen -X -S "TestoE" quit
          host: ${{ secrets.HOST }}
          username: bot
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}

      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: "bot"
          server: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.SSH_SECRET_PEM }}
          local_path: "./*"
          remote_path: "./TestoE-Bot"
          args: "-o ConnectTimeout=5"

      - name: NPM Install
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd TestoE-Bot && npm i
          host: ${{ secrets.HOST }}
          username: bot
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}

      - name: Insert Token
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd TestoE-Bot && sed -i 's/<Token>/${{ secrets.TOKEN}}/g' cfg/config.json
          host: ${{ secrets.HOST }}
          username: bot
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}

      - name: Start Bot
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd TestoE-Bot && bash start.sh
          host: ${{ secrets.HOST }}
          username: bot
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
